name: gitme
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: aboutDavid/gitme
          BRANCH: main
